spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=EST&allowPublicKeyRetrieval=true
    username: root
    password:
    hikari:
      idleTimeout: 500
      connectionTimeout: 15000 
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB

server:
  port: 8080
  servlet:
    contextPath: /demo
